# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='username',
            new_name='name',
        ),
    ]
