# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_auto_20170911_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='indexmodel',
        ),
    ]
