# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_indexmodel_swatch_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('subject', models.TextField()),
            ],
        ),
    ]
