# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0006_feedback_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='startmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('age', models.IntegerField(max_length=2)),
                ('link', models.URLField()),
                ('country', models.CharField(max_length=400)),
                ('theme', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=400)),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
    ]
