# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0007_startmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startmodel',
            name='age',
            field=models.IntegerField(),
        ),
    ]
