# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0008_auto_20170911_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='indexmodel',
        ),
    ]
